on:
  push:
    branches:
      - main
    paths:
      - 'apps/exp001/go/**'

jobs:
  test:
    uses: ./.github/workflows/exp001_go__test.yaml
  lint:
    uses: ./.github/workflows/exp001_go__lint.yaml
